---
application:
  name: "nexusdeploy"
  project: "nexustestqovery"
  organization: "QoveryCommunity"
  publicly_accessible: "true"
routers:
- name: "main-nexusdeploy"
  routes:
  - application_name: "nexusdeploy"
    paths:
    - "/*"
